import { Connection, Keypair, Transaction, LAMPORTS_PER_SOL, sendAndConfirmTransaction } from "@solana/web3.js";
import { pool, zk } from "@soteria1/sdk";
const RPC="http://127.0.0.1:8899", SERVER="http://127.0.0.1:8787", POOL_ID=3, FEE=5000n, DENOM=100000000;
const conn=new Connection(RPC,"confirmed");
const post=(p,b)=>fetch(`${SERVER}${p}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(p+": "+JSON.stringify(j));return j});
const rebuild=async cs=>{const t=await zk.PoseidonMerkleTree.create(20);t.insertMany(cs.map(c=>BigInt(c)));return t;};
const t0=Date.now();
const burner=Keypair.generate();
await conn.confirmTransaction(await conn.requestAirdrop(burner.publicKey, Math.round(0.25*LAMPORTS_PER_SOL)),"confirmed");
const note=pool.randomNote(POOL_ID), commitment=await pool.commitment(note);
const tx=new Transaction().add(pool.depositInstruction(burner.publicKey,POOL_ID,commitment));
tx.feePayer=burner.publicKey;
await sendAndConfirmTransaction(conn,tx,[burner],{commitment:"confirmed"});
await post(`/pools/${POOL_ID}/commitments`,{commitment:commitment.toString()});
const recipient=Keypair.generate().publicKey;
const st=await fetch(`${SERVER}/pools/${POOL_ID}`).then(r=>r.json());
const tBuild=Date.now();
const dt=await rebuild(st.deposits), at=await rebuild(st.association);
const di=st.deposits.indexOf(commitment.toString()), ai=st.association.indexOf(commitment.toString());
const buildMs=Date.now()-tBuild;
const raw=await pool.proveWithdrawRaw({note,depositTree:dt,depositLeafIndex:di,assocTree:at,assocLeafIndex:ai,recipient,fee:FEE},"circuits/build/withdraw_js/withdraw.wasm","circuits/build/withdraw_final.zkey");
const before=await conn.getBalance(recipient);
const w=await post(`/pools/${POOL_ID}/withdraw`,{recipient:recipient.toBase58(),fee:FEE.toString(),proof:raw.proof,publicSignals:raw.publicSignals});
await conn.confirmTransaction(w.signature,"confirmed");
const got=(await conn.getBalance(recipient))-before;
console.log("deposits in pool:", st.deposits.length);
console.log("tree rebuild (2 trees):", buildMs, "ms  (was ~160000 ms)");
console.log("total deposit→claim:", ((Date.now()-t0)/1000).toFixed(1), "s");
console.log("received:", got/LAMPORTS_PER_SOL, "SOL", got===(DENOM-Number(FEE))?"✓ ✅":"✗");
process.exit(got===(DENOM-Number(FEE))?0:1);
